import Sidebar from "@/src/components/sidebar";
import type { Metadata } from "next";
import { auth } from "../api/auth/[...nextauth]/option";
import { redirect } from "next/navigation";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
    const session=await auth();
    if(!session){
        redirect('/login');
    }

  return (
    <div className="min-h-screen flex">
      <Sidebar />

      <main className="flex-1">
        {children}
      </main>
    </div>
  );
}
